---
name: Push workflow
on:
  - push
  - pull_request
jobs:
  tests:
    uses: dbarrosop/nix-common/.github/workflows/z_test.yaml@dbarroso/hasura-storage

  build_docker_image:
    uses: dbarrosop/nix-common/.github/workflows/z_docker_build_image.yaml@dbarroso/hasura-storage
    with:
      NAME: hasura-storage
      VERSION: ${{ github.ref_name }}-${{ github.sha }}

  push_docker_image_to_hub:
    uses: dbarrosop/nix-common/.github/workflows/z_docker_push_to_hub.yaml@dbarroso/hasura-storage
    needs: build_docker_image
    with:
      CONTAINER_NAME: nhost/hasura-storage
      VERSION: ${{ github.ref_name }}-${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # draft your next release notes as pull requests are merged into "main"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        if: github.ref_name == github.event.repository.master_branch
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

