---
name: Push workflow
on:
  - push
  - pull_request
jobs:
  tests:
    uses: dbarrosop/nix-common/.github/workflows/z_test.yaml@hasura-storage

  # build_docker_image:
  #   uses: dbarrosop/nix-common/.github/workflows/z_docker_build_image.yaml@hasura-storage
  #   with:
  #     NAME: hasura-storage
  #     VERSION: ${{ github.ref_name }}-${{ github.sha }}

  # draft your next release notes as pull requests are merged into "main"
  # the configuration is at /.github/release-drafter.yml.
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        if: github.ref_name == github.event.repository.master_branch
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

